baseURL = 'https://saral-hugo-theme.pages.dev/'
languageCode = 'en-us'
title = 'A simple and elegent theme for developers'

theme = 'saral'
pygmentsCodefences = true
pygmentsStyle = "doom-one"

[params]
    logoText = "Saral"
    showHeroImage = true
    isBlogFocused = true
    math = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]

