baseURL = 'https://saral-hugo-theme.pages.dev/'
languageCode = 'en-us'
title = 'Saral : A simple hugo theme'
theme = 'saral'

pygmentsCodefences = true
pygmentsStyle = "github-dark"

[params]
    isBlogFocused = true
    logoText = "Saral"
    showHeroImage = true
    showResumeButton = false
    math = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]