baseURL = 'http://saral-hugo-theme.pages.dev'
languageCode = 'en-us'
title = 'Saral : A simple hugo theme'
author = "dipeshsingh253"

# theme = 'saral'



[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]

[module]
[module.hugoVersion]
  extended = true
  min = "0.92.0"
  max = "0.123.8"
