name = 'Saral'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Embrace simplicity without compromising style.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dipeshsingh253/saral-hugo-theme'

# If you have a running demo of the theme
demosite = 'https://saral-hugo-theme.pages.dev'

# If the theme has a single author
[author]
  name = 'Dipesh Singh'
  homepage = 'dipesh.dev'